version: '3.7'

services:
  api:
    build: .
    container_name: dobrynya-mock-api
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db/db.sqlite3
    command: >
      gunicorn app.main:app 
      -k uvicorn.workers.UvicornWorker 
      --bind 0.0.0.0:8000 
      --workers 4 
      --timeout 120
