version: '3.9'

services:
  api:
    build: .
    container_name: dobrynya-mock-api
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db/db.sqlite3
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
